networks:
  soul-network:
    driver: bridge

services:
  php: &laravel
    build:
      context: .
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '.:/www'
      - ./php.dev.ini:/usr/local/etc/php/conf.d/xdebug.ini
    command: php artisan serve --host=0.0.0.0
    user: 'sail'
    working_dir: /www
    environment:
      - 'PHP_IDE_CONFIG=${PHP_IDE_CONFIG}'
      - 'NEO4J_HOST=neo4j'
      - 'NEO4J_PORT=7687'
      - 'NEO4J_USER=neo4j'
      - 'NEO4J_PASSWORD=${NEO4J_PASSWORD:-secret}'
      - 'NEO4J_DATABASE=neo4j'
    ports:
      - '${FORWARD_PHP_PORT}:8000'
    networks:
      - soul-network
    depends_on:
      - neo4j

  reverb:
    <<: *laravel
    command: 'php artisan reverb:start'
    ports:
      - '${FORWARD_REVERB_PORT}:8080'
    networks:
      - soul-network

  queue:
    <<: *laravel
    command: 'php artisan queue:work'
    ports:
      - '0:8080'
    networks:
      - soul-network

  node:
    image: node:21-alpine3.18
    user: node
    working_dir: /frontend
    environment:
      - NODE_ENV=development
    volumes:
      - '.:/frontend'
    command: 'npm run dev -- --host=0.0.0.0 --port=${FORWARD_NODE_PORT}'
    ports:
      - ${FORWARD_NODE_PORT}:${FORWARD_NODE_PORT}
    networks:
      - soul-network

  redis:
    image: redis:7.2-alpine
#    ports:
#      - '${FORWARD_REDIS_PORT}:6379'
    networks:
      - soul-network

  neo4j:
    image: neo4j:5.15-community
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-secret}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
      - NEO4J_dbms_connector_http_listen__address=0.0.0.0:7474
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
    ports:
      - '${FORWARD_NEO4J_HTTP_PORT:-7474}:7474'  # HTTP Web Interface
      - '${FORWARD_NEO4J_BOLT_PORT:-7687}:7687'  # Bolt Protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - soul-network

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local
